---
- name: Bootstrap Debian Machine
  hosts: debian
  become: yes
  tasks:

    - name: Update APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade installed packages
      apt:
        upgrade: dist

    - name: Install essential packages
      apt:
        name:
          - sudo
          - vim
          - curl
          - git
          - tmux
          - neovim
          - htop
          - docker.io
          - docker-compose
          - ufw
        state: present

    - name: Add VS Code repository
      shell: |
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
        sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" | sudo tee /etc/apt/sources.list.d/vscode.list
      args:
        creates: /etc/apt/sources.list.d/vscode.list

    - name: Install VS Code
      apt:
        name: code
        state: present
        update_cache: yes

    - name: Enable and configure UFW firewall
      ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Allow SSH through firewall
      ufw:
        rule: allow
        name: OpenSSH
