---
- name: Bootstrap Debian Machine
  hosts: debian
  become: true
  tasks:

    - name: Update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install essential packages
      apt:
        name:
          - git
          - vim
          - tmux
          - htop
          - curl
          - neovim
          - docker.io
          - code # Visual Studio Code
        state: present

    - name: Ensure the SSH directory exists
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Configure firewall rules
      ufw:
        rule: allow
        name: OpenSSH

    - name: Enable and start UFW firewall
      ufw:
        state: enabled

    - name: Set up passwordless sudo
      copy:
        dest: "/etc/sudoers.d/{{ ansible_user }}"
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'

    - name: Restart SSH service
      systemd:
        name: ssh
        state: restarted
